version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: paytracker-db
    restart: always
    environment:
      POSTGRES_DB: paytracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
